const menuList=[

    {
        title:'首页',//菜单名称
        key:'/home',//对应path
        icon:'/home',//图标名称
        isPublic:true//公开的
    },
    {
        title:'商品',//菜单名称
        key:'/product',//对应path
        icon:'/appstore',//图标名称
        children:[
            {
                title:'品类管理',
                key:'/product/category',
                icon:'/bars'
            },
            {
                title:'商品管理',
                key:'/product/product',
                icon:'/tool'
            }
        ]
    },
    {
        title:'用户管理',
        key:'/user',
        icon:'/user',
    },
    {
        title:'角色管理',
        key:'/role',
        icon:'/role'
    },
    {
        title:'图形图标',
        key:'/charts',
        icon:'/area-chart',
        children:[
            {
                title:'柱形图',
                key:'/bar',
                icon:'/bars'
            },
            {
                title:'折线图',
                key:'/line',
                icon:'/line'
            },
            {
                title:'饼状图',
                key:'/pie',
                icon:'/pie'
            }
        ]
    }
]

export default menuList